# Generated by Django 5.1.7 on 2025-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='knqf_level',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='qualification',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='anything_else',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='highest_academic_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='how_you_heard_about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='name_of_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='year_of_completion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
